INSERT INTO USERS(ID, VERSION, PASSWORD, USERNAME) VALUES (USERS_SEQ.nextval,1,'adminpass','admin');
INSERT INTO USERS(ID, VERSION, PASSWORD, USERNAME) VALUES (USERS_SEQ.nextval,1,'111111','mahdi');
INSERT INTO ROLES(ID, VERSION, NAME) VALUES (ROLES_SEQ.nextval,1,'admin');
INSERT INTO ROLES(ID, VERSION, NAME) VALUES (ROLES_SEQ.nextval,1,'user');
INSERT INTO USERS_ROLES(USER_ID, ROLES_ID) VALUES (1,1);
INSERT INTO USERS_ROLES(USER_ID, ROLES_ID) VALUES (1,2);
INSERT INTO USERS_ROLES(USER_ID, ROLES_ID) VALUES (2,2);
commit ;